### PR TITLE
Allow --prefix to work

### PR DESCRIPTION
**Pull request by dsblank**
This PR makes a change from `sys.prefix` to `self.install_base` to allow top-level command to set the --prefix or --install_dir.

### CODE REVIEW

**Comment by dsblank** [comment]
There are some things I don't understand about how setup works, removing files, --user, and --prefix. There may be more than what this PR does that is needed.

**Comment by dsblank** [comment]
Ok, I think this is the correct fix.

**Comment by jasongrout** [comment]
Thanks @dsblank!

**Comment by dsblank** [comment]
Thanks folks, and welcome back @blink1073 ! Hope all is going well.

Re: this PR... there are probably better ways of handling setuptools, and maybe an expert will look at this someday. But it is working for me when using `--prefix=` now.

**Pull request merged**
