### PR TITLE
Add flit backend

### PR DESCRIPTION
**Pull request by blink1073**
- [x] Add build backend based on flit
- [x] Add pre and post build editable config
- [x] Add wheel test with data files
- [x] Add editable test with data files
- [ ] Add an alias for `flit install --symlink`
- [ ] Add documentation

### CODE REVIEW

**Comment by blink1073** [comment]
Notes for docs:

When using the `flit` backend, you must specify the following fields in `pyproject.toml`:

```toml
[project]
name = "foo"
version = "0.1.0"
description = "foo package"
```

Data files can be specified as:

```toml
[tool.jupyter-packaging.external-data]
directory = "data"
```

Data files are *copied* at build time in editable mode.  We can support linking by providing an alias to `flit install --symlink`.  However, we need to think about how this interacts with `jupyter labextension develop`.

You can use the same builder and args in editable mode, or use the following specific keys:

```toml
[tool.jupyter-packaging.editable-builder]
factory = "foo.main"

[tool.jupyter-packaging.editable-build-args]
fizz = "buzz"
```

**Comment by blink1073** [comment]
To summarize the status:

- Packages that only ship static config files can use `flit` directly now that `data_files` support has landed.  This includes kernels and server extensions.
- Packages that have a build step with static assets, like Jupyter Server's JavaScript assets can use this backend
- Jupyter LabExtensions are trickier - currently `jupyter labextension develop` creates a symlink for a directory.  This is incompatible with PEP 600 *and* `flit install --symlink`.  Due to the limitations of PEP 660, `pip install -e .` results in *copied* data files.  Using `flit install --symlink` (or an alias provided by `jupyter_packaging`) uses symlinks for the files in the data directory. 
 
I think the best path forward is for `jupyter labextension develop` to be an alias for `flit install --symlink`, and to update the way the extension JavaScript files are built and loaded.  The file names should be stable, but the server needs to know that they should not be cached.   The extension in `jupyterlab_server` could be updated to not cache a file if the path is a symlink.

**Comment by blink1073** [comment]
cc @fcollonval @jasongrout @jtpio @bollwyvl

**Comment by bollwyvl** [comment]
Very nice stuff, looking forward to perusing it.

**Comment by fcollonval** [comment]
Awesome thanks @blink1073 

> I think the best path forward is for jupyter labextension develop to be an alias for flit install --symlink, and to update the way the extension JavaScript files are built and loaded. The file names should be stable, but the server needs to know that they should not be cached. The extension in jupyterlab_server could be updated to not cache a file if the path is a symlink.

My concern here is that during development, it is quite common to change the list of source files and the dependencies. If we switch to symlinking at the file level, this will require `jupyter labextension build --development` and `jupyter labextension watch` to update the symlinks if the list of files changes, isn't it? And if going that way, this probably means we could keep the hash to avoid caching as we could always update the symlinks.

**Comment by blink1073** [comment]
Yeah that's a fair way to do it.  I'll finish this up as planned and leave it to y'all to handle the lab extension migration.  Note that this is a new backend, so the cookiecutter would have to be changed to opt in to it.

**Comment by blink1073** [comment]
Alternatively, we may be able to add `external_data` support to [`setuptools`](https://github.com/pypa/setuptools/issues/3191).

**Comment by blink1073** [comment]
Closing this because it would be too awkward moving forward to support two build backend types in one repo.  I think whichever way we move forward it should be with a new repo, cf https://github.com/jupyterlab/team-compass/issues/146

**Pull request closed without merging**
