### PR TITLE
Clean up handling of version info

### PR DESCRIPTION
**Pull request by jtpio**
Fixes jupyter/jupyter-packaging#81
Addresses jupyterlab/jupyterlab#10111

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by yuvipanda** [comment]
Is this doing the version requirement bump *and* removing the problematic function at the same time?

**Comment by blink1073** [comment]
We had been relying on https://github.com/pypa/setuptools/blob/main/CHANGES.rst#changes-15, this relaxes that requirement.

**Comment by yuvipanda** [comment]
Ah, ok. I don't fully understand it, but I think that's most of the packaging magic that happens here :D I'm glad y'all got it tho

**Pull request merged**
